Metrics/AbcSize:
  Max: 18

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 110
  AllowURI: true

Style/SymbolArray:
  MinSize: 3

Style/ClassVars:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Naming/UncommunicativeMethodParamName:
  MinNameLength: 1
  AllowNamesEndingInNumbers: false

