language: ruby
rvm:
  # List is from https://www.ruby-lang.org/en/downloads/branches/
  - "1.9.3"
  - "2.0.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
matrix:
  allow_failures:
  - rvm: "1.9.3"
  - rvm: "2.0.0"
  - rvm: "2.1"
before_install: gem update --system
script:
  - bundle exec rake test
  - bundle exec rake rubocop
