name: feature.md
description: Submit a proposal for a new feature
title: '[Feature]: '
labels: [':rocket: Feature Request']
body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for taking the time to suggest a new feature!
        We kindly ask that you search to see if an issue [already exists](https://github.com/razorpay/razorpay-ruby/issues?q=is%3Aissue+sort%3Acreated-desc+) for your feature.
        We are also happy to accept contributions from our users.
  - type: textarea
    id: description
    attributes:
      label: '🚀 Feature Proposal'
      description: 
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Suggested Solution
      description: 
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description:
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Additional Information
      description:
    validations:
      required: true
