name: CI
on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
    branches:
      - master
jobs:
 test:
  runs-on: ubuntu-latest
  #strategy:
   #matrix:
    #ruby-version: 3.1
    
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Ruby latest
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
    - name: Install dependencies
      run: bundle install
    - name: Run tests and collect coverage
      run: bundle exec rake
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        coveragePath: ${{ github.workspace }}/coverage
